FROM python:3.11-slim

WORKDIR /app

COPY src ./src
COPY requirements-serve.txt .
RUN pip install --no-cache-dir torch --index-url https://download.pytorch.org/whl/cpu \
    && pip install --no-cache-dir pydantic google-cloud-storage fastapi uvicorn

ENV MODEL_PATH=/app/checkpoints/model.pt

EXPOSE 8080

CMD ["uvicorn", "src.serve:app", "--host", "0.0.0.0", "--port", "8080"]
